@startuml ComunicationDiagram
skinparam packageStyle rectangle
skinparam shadowing false
skinparam backgroundColor #F9F9F9
skinparam packageBackgroundColor #DDDDDD
skinparam packageBorderColor #000000
skinparam arrowColor #000000
skinparam arrowThickness 2

package "RelationshipDB" <<Database>> {
}

package "MetricsDB" <<Database>> {
}

[Src] -> [Puml Generator] : RE-Tool 1
[Puml Generator] -> [file.puml] : 2
[file.puml] -> [Parser] : 3
[Parser] -> [Filter Parser] : 4
[Filter Parser] -> [Observer] : 5
[Observer] --> [RelationshipDB] : 6
[Metric Calculator] --> [RelationshipDB] : queries 7
[Metric Calculator] -> [Result Observer] : 8
[Result Observer] -> [MetricsDB] : 9
[MetricsDB] <-- [Metrics Evaluator] : 10
[Metrics Evaluator] --> [Veredict] : 11

@enduml