@startuml ComunicationDiagram
skinparam packageStyle rectangle
skinparam shadowing false
skinparam backgroundColor #F9F9F9
skinparam packageBackgroundColor #DDDDDD
skinparam packageBorderColor #000000
skinparam arrowColor #000000
skinparam arrowThickness 2

package "RelationshipDB" <<Database>> {
}

package "MetricsDB" <<Database>> {

}

[Src] -> [Puml Generator] : RE-Tool 1
[Puml Generator] -> [file.puml] : 2
[file.puml] -> [Parser] : 3
[Parser] -> [Observer] : 4
[Observer] --> [RelationshipDB] : 5
[Result Queries] --> [RelationshipDB] : queries 6
[Result Queries] -> [Result Observer] : 7
[Result Observer] -> [MetricsDB] : 8
[MetricsDB] <-- [Metrics Evaluator] : 9
[Metrics Evaluator] --> [Veredict] : 10

@enduml