@startuml ComunicationDiagram
skinparam packageStyle rectangle
skinparam shadowing false
skinparam backgroundColor #F9F9F9
skinparam packageBackgroundColor #DDDDDD
skinparam packageBorderColor #000000
skinparam arrowColor #000000
skinparam arrowThickness 2

package "RelationshipDB" <<Database>> {
}

package "MetricsDB" <<Database>> {

}

[Src] -> [.puml] : RE-Tool 1
[.puml] -> [Parser] : 2
[Parser] -> [Obs Graph] : 3
[Obs Graph] --> [RelationshipDB] : 4
[Metrcis Collecter] --> [RelationshipDB] : queries 5
[Metrcis Collecter] -> [MetricsDB] : 6
[MetricsDB] --> [Metrics Evaluator] : 7
[Metrics Evaluator] --> [Veredict] : 8

@enduml