@startuml DAG
skinparam packageStyle rectangle
skinparam shadowing false
skinparam backgroundColor #F9F9F9
skinparam packageBackgroundColor #DDDDDD
skinparam packageBorderColor #000000
skinparam arrowColor #000000
skinparam arrowThickness 2

abstract class PUML_Parser {
    Parse(file, PUML_Obs)
}
abstract class PUML_Parser_Obs {
    Parse(file, PUML_Obs)
}
class ply
class regex
class pyparsing
class cypherGraphDB
class gremlinGraphDB
class print 
class composableObserver
class main {
    parser = PumlParserFactory(ParserName) 
    observer = PumlObsFactory(ObsName)
    parser.parse(file,observer)
     
}

PUML_Parser <|-- ply   
PUML_Parser <|-- regex  
PUML_Parser <|-- pyparsing  

PUML_Parser_Obs <|-- cypherGraphDB
PUML_Parser_Obs <|-- gremlinGraphDB
PUML_Parser_Obs <|-- print
PUML_Parser_Obs <|-- composableObserver

PUML_Parser -> PUML_Parser_Obs : (coupling)
@enduml