@startuml
participant main
participant "API" as API
participant "Puml Generator" as PumlGenerator
participant "Parser" as Parser
participant "Filter Parser" as FilterParser
participant "Observer" as Observer
participant "RelationshipsDB" as relationshipsDB
participant "Result Queries" as ResultQueries
participant "Result Observer" as ResultObserver
participant "MetricsDB" as metricsDB
participant "Metrics Evaluator" as MetricsEvaluator
participant "Veredict" as Veredict

API -> main: puml_generator

API -> main: parser

API -> main: FilterParser

API -> main: Observer

API -> main: result_queries

API -> main: result_observer

main -> PumlGenerator: generate_puml()

PumlGenerator -> main: file.puml

main -> Observer: create_observer()

main -> Observer: set_mode(MODE)

main -> Parser: parse(file.puml, observer)

activate Parser

loop
    Parser -> FilterParser: relationship
    FilterParser -> Observer: relationship
    Observer -> relationshipsDB: store\nrelationship
end
deactivate Parser

main -> ResultObserver: create_result_observer()
main -> ResultQueries: resolve_query(result_observer)

activate ResultQueries

loop
    ResultQueries -> relationshipsDB: queries
    ResultQueries -> ResultObserver: result
    ResultObserver -> metricsDB: store\nmetrics
end
deactivate ResultQueries

MetricsEvaluator -> metricsDB: metrics
MetricsEvaluator -> Veredict: veredict

@enduml

