name: CDDE Check

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  run-cdde:
    runs-on: ubuntu-latest
    services:
      neo4j:
        image: neo4j:5.22
        ports:
          - 7687:7687
        env:
          NEO4J_AUTH: none
    steps:
      - name: Checkout tool in main
        uses: actions/checkout@v4
        with:
          ref: main

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install Poetry
        run: pip install poetry==1.8.4

      - name: Install dependencies
        run: poetry install

      - name: Wait for Neo4j
        run: |
          for i in {1..30}; do
            if nc -z neo4j 7687; then
              echo "Neo4j is ready"
              break
            fi
            echo "Waiting for Neo4j..."
            sleep 2
          done

      - name: Run CDDE
        run: |
          REPO="https://github.com/${{ github.repository }}"
          PR_NUMBER="${{ github.event.pull_request.number }}"
          poetry run cdde run "$REPO" "$PR_NUMBER" src/queries/cypher.yml src/queries/derived_metrics.yml src/queries/sqlite.yml --main-branch main --exclude Samples --uri bolt://neo4j:7687
