name: Render PlantUML Diagrams

on:
  push:
    branches:
      - main

jobs:
  render-diagrams:
    # Prevenir bucles infinitos
    if: ${{ github.actor != 'github-actions[bot]' }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          persist-credentials: false  # Evitar conflictos con credenciales

      - name: Set Up Git User
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Set Up Authentication
        env:
          TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git remote set-url origin https://x-access-token:${TOKEN}@github.com/${{ github.repository }}.git

      - name: Set Up Java Environment
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'

      - name: Install PlantUML
        run: |
          sudo apt-get update
          sudo apt-get install -y plantuml

      - name: Generate Diagrams
        run: |
          find . \( -name "*.puml" -o -name "*.plantuml" \) -print0 | xargs -0 -I{} plantuml {}

      - name: Commit Diagrams
        run: |
          git add .
          git commit -m "Automated rendering of PlantUML diagrams" || echo "No changes to commit"

      - name: Push Changes
        run: |
          git push origin HEAD:${{ github.ref }}
        continue-on-error: true  # Esto evita que falle si ya no puede hacer push de los cambios
